/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.bw.sharedresource.activespace.design.provider;

import com.tibco.bw.sharedresource.activespace.model.assr.util.AssrAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AssrItemProviderAdapterFactory extends AssrAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AssrItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.bw.sharedresource.activespace.model.assr.Metaspace} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetaspaceItemProvider metaspaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.bw.sharedresource.activespace.model.assr.Metaspace}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetaspaceAdapter() {
		if (metaspaceItemProvider == null) {
			metaspaceItemProvider = new MetaspaceItemProvider(this);
		}

		return metaspaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.bw.sharedresource.activespace.model.assr.Space} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpaceItemProvider spaceItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.bw.sharedresource.activespace.model.assr.Space}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpaceAdapter() {
		if (spaceItemProvider == null) {
			spaceItemProvider = new SpaceItemProvider(this);
		}

		return spaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.bw.sharedresource.activespace.model.assr.SpaceConnection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpaceConnectionItemProvider spaceConnectionItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.bw.sharedresource.activespace.model.assr.SpaceConnection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpaceConnectionAdapter() {
		if (spaceConnectionItemProvider == null) {
			spaceConnectionItemProvider = new SpaceConnectionItemProvider(this);
		}

		return spaceConnectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.bw.sharedresource.activespace.model.assr.SpaceFieldDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpaceFieldDefinitionItemProvider spaceFieldDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.bw.sharedresource.activespace.model.assr.SpaceFieldDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpaceFieldDefinitionAdapter() {
		if (spaceFieldDefinitionItemProvider == null) {
			spaceFieldDefinitionItemProvider = new SpaceFieldDefinitionItemProvider(this);
		}

		return spaceFieldDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.bw.sharedresource.activespace.model.assr.SpaceKeyDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpaceKeyDefinitionItemProvider spaceKeyDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.bw.sharedresource.activespace.model.assr.SpaceKeyDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpaceKeyDefinitionAdapter() {
		if (spaceKeyDefinitionItemProvider == null) {
			spaceKeyDefinitionItemProvider = new SpaceKeyDefinitionItemProvider(this);
		}

		return spaceKeyDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.bw.sharedresource.activespace.model.assr.SpaceIndexDefinition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpaceIndexDefinitionItemProvider spaceIndexDefinitionItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.bw.sharedresource.activespace.model.assr.SpaceIndexDefinition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpaceIndexDefinitionAdapter() {
		if (spaceIndexDefinitionItemProvider == null) {
			spaceIndexDefinitionItemProvider = new SpaceIndexDefinitionItemProvider(this);
		}

		return spaceIndexDefinitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.bw.sharedresource.activespace.model.assr.DynamicUIField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DynamicUIFieldItemProvider dynamicUIFieldItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.bw.sharedresource.activespace.model.assr.DynamicUIField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDynamicUIFieldAdapter() {
		if (dynamicUIFieldItemProvider == null) {
			dynamicUIFieldItemProvider = new DynamicUIFieldItemProvider(this);
		}

		return dynamicUIFieldItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (metaspaceItemProvider != null) metaspaceItemProvider.dispose();
		if (spaceItemProvider != null) spaceItemProvider.dispose();
		if (spaceConnectionItemProvider != null) spaceConnectionItemProvider.dispose();
		if (spaceFieldDefinitionItemProvider != null) spaceFieldDefinitionItemProvider.dispose();
		if (spaceKeyDefinitionItemProvider != null) spaceKeyDefinitionItemProvider.dispose();
		if (spaceIndexDefinitionItemProvider != null) spaceIndexDefinitionItemProvider.dispose();
		if (dynamicUIFieldItemProvider != null) dynamicUIFieldItemProvider.dispose();
	}

}
